web/VAV.Web/ViewModels/Bond/BondRatingHistViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using VAV.Model.Data;
using VAV.Model.Data.Bond;
using VAV.Web.ViewModels.Report;
using VAV.DAL.Report;
using VAV.DAL.ResearchReport;
using System.Data;

namespace VAV.Web.ViewModels.Bond
{
    public class BondRatingHistViewModel
    {
        public string BondCode { get; private set; }
        public List<BondRatingHist> RatingHistData { get; private set; }

        public BondRatingHistViewModel(string bondCode, BondReportRepository repository, ResearchReportRepository CMARepository)
        {
            RatingHistData = repository.GetBondRatingByCode(bondCode);
            var idlist = RatingHistData.Select(r => r.RATE_ID.ToString()).ToList();

            if (idlist != null && idlist.Count() != 0)
            {
                var ids = idlist.Aggregate((a, b) => a + "," + b).ToString();
                var dataTable = CMARepository.CheckCommonFileExsit(ids, "RATE_REP_DATA", "RATE_ID");

                if (dataTable != null)
                {
                    foreach (DataRow row in dataTable.Rows)
                        RatingHistData.Where(r => r.RATE_ID == Convert.ToInt64(row["RATE_ID"])).ToList().ForEach(r => r.ContainFile = true);
                }
            }

            BondCode = bondCode;
        }
    }
}

web/VAV.Web/Controllers/BondReportController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.Practices.Unity;
using VAV.DAL.Common;
using VAV.DAL.Services;
using VAV.Model.Data.Bond;
using VAV.Model.Data;
using VAV.Model.Data.ZCX;
using VAV.Web.Localization;
using VAV.Web.Common;
using VAV.Web.Extensions;
using VAV.Web.ViewModels.Bond;
using VAV.DAL.Report;
using VAV.DAL.Fundamental;
using VAV.DAL.ResearchReport;
using System.Data;
using VAV.Model.Chart;
using log4net;
using VAV.Entities;

namespace VAV.Web.Controllers
{
    /// <summary>
    /// Report Controller
    /// </summary>
    public class BondReportController : BaseController
    {

        [Dependency]
        public BondReportRepository BondReportRepository { get; set; }

        [Dependency]
        public ZCXRepository ZcxRepository { get; set; }

        [Dependency]
        public ResearchReportRepository CmaRepository { get; set; }

        [Dependency]
        public BondInfoRepository BondInfoRepository { get; set; }

        #region Issue Rates
        [Localization]
        public ActionResult GetRateOfIssuesReport(int id)
        {
            ReportInfo reportInfo = ReportService.GetReportInfoById(id);
            var startDate = new DateTime(DateTime.Now.Year - 1, DateTime.Now.Month, 1);
            var bondRateRepo = ReportService.GetBondIssueRatesRepo(new BondIssueParams
            {
                StartDate = startDate,
                BondType = "BTB",
                Term = "7Y",
                IsFloat = "n",
                Rating = "All"
            }).ToList();
            var bondRateRepo2 = ReportService.GetBondIssueRatesRepo(new BondIssueParams
            {
                StartDate = startDate,
                BondType = "PBB",
                Term = "7Y",
                IsFloat = "n",
                Rating = "All"
            }).ToList();

            var bondIssueReport = new BondIssueRateReport(reportInfo.ReportId)
            {
                Name = reportInfo.DisplayName,
            };

            bondIssueReport.InitOrUpdate(bondRateRepo);
            bondIssueReport.InitOrUpdate(bondRateRepo2);
            var themeName = ThemeHelper.GetTheme(Request);
            bondIssueReport.Chart.Theme = themeName;

            return View("RateOfIssues", bondIssueReport);
        }

        [Localization]
        public ActionResult AddBond(int reportId, string displayName, DateTime? date, string bondType, string term, string couponType, string rating, string grid)
        {
            var serializer = new JavaScriptSerializer();

            if (grid.Contains("&quot"))
                grid = System.Web.HttpUtility.HtmlDecode(grid);
            var g = serializer.Deserialize(grid, typeof(List<BondIssueRate>)) as List<BondIssueRate>;

            var param = new BondIssueParams
            {
                StartDate = date ?? new DateTime(DateTime.Now.Year, 1, 1),
                BondType = bondType,
                Term = term,
                IsFloat = couponType,
                Rating = rating,
            };

            var bondRateRepo = ReportService.GetBondIssueRatesRepo(param).ToList();

            var bondIssueReport = new BondIssueRateReport(reportId)
            {
                Name = displayName,
                Grid = g,
                IsAllRating = rating == "All"
            };

            bondIssueReport.InitOrUpdate(bondRateRepo);
            var themeName = ThemeHelper.GetTheme(Request);
            bondIssueReport.Chart.Theme = themeName;

            return PartialView("_IssueRatesStatistical", bondIssueReport);
        }

        [Localization]
        public ActionResult DeleteBond(int reportId, string displayName, DateTime? date, string bondType, string term, string couponType, string rating, string grid, string itemName)
        {
            var serializer = new JavaScriptSerializer();

            if (grid.Contains("&quot"))
                grid = System.Web.HttpUtility.HtmlDecode(grid);
            var g = serializer.Deserialize(grid, typeof(List<BondIssueRate>)) as List<BondIssueRate>;

            if (g != null)
                g.RemoveAll(b => b.ItemName == itemName);

            var bondIssueReport = new BondIssueRateReport(reportId)
            {
                Name = displayName,
                Grid = g,
                IsAllRating = rating == "All"
            };

            bondIssueReport.UpdateChartOnly(g);
            var themeName = ThemeHelper.GetTheme(Request);
            bondIssueReport.Chart.Theme = themeName;

            return PartialView("_IssueRatesStatistical", bondIssueReport);
        }

        #endregion

        ILog _log = LogManager.GetLogger(typeof(BondReportController));

        #region Issue Amount Report
        [Localization]
        public ActionResult GetIssueAmountReport(int id)
        {
            _log.Error("GetIssueAmountReport start:"+DateTime.Now);
            ReportInfo reportInfo = ReportService.GetReportInfoById(id);
            _log.Error("GetIssueAmountReport 2:" + DateTime.Now);
            IEnumerable<BondIssueAmount> topGrid;
            IEnumerable<BondDetail> bottomGrid;
            GetIssueAmountReportData(null, out topGrid, out bottomGrid);
            _log.Error("GetIssueAmountReport 3:" + DateTime.Now);
            var bondIssueAmounts = topGrid as BondIssueAmount[] ?? topGrid.ToArray();
            var model = new BondIssueAmountReport(
                    reportInfo.ReportId,
                    reportInfo.DisplayName,
                    Resources.Global.Unit_Option_100M,
                    bondIssueAmounts, bottomGrid);
            _log.Error("GetIssueAmountReport 4:" + DateTime.Now);
            int year = DateTime.Now.Year;
            int month = 12;

            if (DateTime.Now.Month == 1)
                year = DateTime.Now.Year - 1;
            else
                month = DateTime.Now.Month - 1;

            ViewData["StartDate"] = new DateTime(year, month, 1).ToString("yyyy-MM-dd");
            ViewData["EndDate"] = DateTime.Now.ToString("yyyy-MM-dd");
            ViewData["Type"] = ConstValues.Type_Bond_Class;
            ViewData["TypeList"] = bondIssueAmounts.Count() == 0 ? "" : string.Join(",", bondIssueAmounts.Select(re => re.Type).ToList());
            ViewData["SubType"] = "";
            ViewData["UseSubType"] = false;
            ViewData["UseSecType"] = "n";
            ViewData["Unit"] = ConstValues.Unit_100M;
            ViewData["TopGridName"] = model.TopGridName;
            ViewData["TypeValue"] = (model.TopGrid == null || model.TopGrid.Count() == 0) ? "" : model.TopGrid.Select(t => t.Type).First();
            ViewData["SubTypeValue"] = "";
            ViewData["TopGridName"] = model.TopGridName;
            ViewData["BottomGridName"] = model.BottomGridName;
            _log.Error("GetIssueAmountReport 5:" + DateTime.Now);
            return View("IssueAmountReport", model);
        }

        [Localization]
        public ActionResult GetIssueAmountReportContent(int reportId, string reportName, string type, string typeList, string useSubType, string subType, string startDate, string endDate, string unit)
        {
            var param = new BondIssueAmountParams
            {
                Type = type,
                TypeList = typeList.Split(',').ToList(),
                UseSubType = useSubType == "true",
                SubType = subType,
                StartDate = DateTime.Parse(startDate),
                EndDate = DateTime.Parse(endDate),
                Unit = unit
            };

            IEnumerable<BondIssueAmount> topGrid;
            IEnumerable<BondDetail> bottomGrid;
            GetIssueAmountReportData(param, out topGrid, out bottomGrid);
            var model = new BondIssueAmountReport(
                    reportId,
                    reportName,
                    HtmlUtil.GetUnitOptionByKey(unit), // for display
                    topGrid, bottomGrid);

            if (topGrid == null || topGrid.Count() == 0)
            {
                return new EmptyResult();
            }

            ViewData["StartDate"] = param.StartDate;
            ViewData["EndDate"] = param.EndDate;
            ViewData["Type"] = param.Type;
            ViewData["TypeList"] = typeList;
            ViewData["SubType"] = param.SubType;
            ViewData["UseSubType"] = param.UseSubType && type != subType;
            ViewData["UseSecType"] = (param.UseSubType && type != subType) ? "y" : "n";
            ViewData["Unit"] = param.Unit;
            ViewData["TopGridName"] = model.TopGridName;
            ViewData["TypeValue"] = model.TopGrid.Select(t => t.Type).First();
            ViewData["SubTypeValue"] = "";
            ViewData["TopGridName"] = model.TopGridName;
            ViewData["BottomGridName"] = model.BottomGridName;

            return View("_IssueAmountReportContent", model);
        }

        [Localization]
        public ActionResult RefreshBondDetail(int reportId, string type, string typeValue, string subType, string subTypeValue, string useSubType, string isParent, string startDate, string endDate, string unit,  string itemList, int startPage, int pageSize)
        {
            var bottomGrid = ReportService.GetBondDetailByTypeAndSubType(
                new BondDetailParams
                {
                    Type = type,
                    TypeValue = typeValue,
                    SubType = subType,
                    SubTypeValue = subTypeValue,
                    UseSubType = useSubType == "true",
                    IsParent = isParent == "true",
                    StartDate = DateTime.Parse(startDate),
                    EndDate = DateTime.Parse(endDate),
                    ItemList = itemList,
                    StartPage = startPage,
                    PageSize = pageSize
                });

web/VAV.Web/Views/BondReport/BondRatingHist.cshtml
@model VAV.Web.ViewModels.Bond.BondRatingHistViewModel
@{
    string emptyMessageId = "emptyMessage" + ViewBag.ID;
    ViewBag.Name = @Resources.Global.Bond_History_Rating;
}

<div class="colorBlock-header">
    <span class="colorBlock-header-span">@ViewBag.Name</span>
</div>
@if (Model.RatingHistData.Count == 0)
{
    <div id="@emptyMessageId" style="margin-left:10px;">@Resources.Global.Empty_Result</div>
}
else
{
    <div>
    <table class="datatable Zebra" style="cursor: pointer;">
        <thead>
            <tr class="hr">
                <th>@Resources.Global.Bond_Rating_Date</th>
                <th>@Resources.Global.Bond_Rating_Type</th>
                <th>@Resources.Global.Bond_Rating_Class</th>
                <th>@Resources.Global.Bond_Rating_Orgnization</th>
                <th>@Resources.Global.Bond_Rating</th>
                <th>@Resources.Global.Bond_Rating_Prospect</th>
                <th>@Resources.Global.Bond_Rating_Report</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var f in Model.RatingHistData)
            {
                var matureDate = f.RATE_DATE == null ? "" : f.RATE_DATE.ToString("yyyy-MM-dd");
                <tr>
                    <td>@matureDate</td>
                    <td style="text-align:left;">@f.RATE_TYPE</td>
                    <td style="text-align:left;">@f.RATE_CLS</td>
                    <td style="text-align:left;">@f.RATE_ORG</td>
                    <td style="text-align:left;">@f.RATE</td>
                    <td style="text-align:left;">@f.RATE_PROS</td>
                    <td style="text-align:left;">
                        @if (@f.ContainFile)
                        {
                            <a class="link" href='/BondReport/DownloadRatingFile/@f.RATE_ID'>@f.RATE_TITLE</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </div>
}
<div>@Resources.Global.Source</div>

web/VAV.Web/Views/BondReport/IssueAmountReport.cshtml
@using System.Web.Script.Serialization
@using VAV.Web.Common;
@using VAV.Web.ViewModels.Bond;

@model BondIssueAmountReport
@{
    var datePickerId = "datePicker" + @Model.ID;
    var endDatePickerId = "endDatePicker" + @Model.ID;
    var contentDivId = "contentDiv" + @Model.ID;

    var typeSelectId = "tselect" + @Model.ID;
    var secTypeSelectId = "secTypeSelectId" + @Model.ID;

    var unitSelectId = "uselect" + @Model.ID;

    var startDate = ViewData["StartDate"];
    var endDate = ViewData["EndDate"];
    
    var issueAmountReportUrl = VirtualPathUtility.ToAbsolute("~/BondReport/GetIssueAmountReportContent");
    var refreshBondDetailUrl = VirtualPathUtility.ToAbsolute("~/BondReport/RefreshBondDetail");
    var updateSubTypeOptionsUrl = VirtualPathUtility.ToAbsolute("~/BondReport/UpdateSubTypeOptions");
    var s = new JavaScriptSerializer();
    var topChart = s.Serialize(Model.Chart);

    Layout = null;
}
<div class="colorBlock" style="min-width:980px;">
    <div id="filterDiv" style="margin: 5px 0px 0px 10px; height:27px;">
        <div style="float: left;">
            @Resources.Global.Report_Query_From
            <input type="text" id="@datePickerId" value="@startDate" class="dateInput" readonly/>
            <label>@Resources.Global.Report_Query_End</label>
            <input type="text" id="@endDatePickerId" value="@endDate" class="dateInput" readonly/>
            <label>@Resources.Global.Report_Type</label>
            <select id="@typeSelectId" class="medium2Select" onchange="UpdateSubTypeOptions(@Model.ID)">
                @foreach (var o in HtmlUtil.CookOptions("bond_market_classify"))
                {
                    <option value="@o.ID">@o.Name</option>    
                }
            </select>
        </div>

        <div style="float:left;">
            <div class="colorBlock">
                <div id="optionDiv">@Html.DropDownList("subTypeOptionSelect", UIStaticDataCache.Instance.AssetClass, new { @class = "largeSelect", multiple = "multiple" })</div>
            </div>
            <input type="hidden" id="selectedOptionCount" value="0"/>
        </div>

        <div style="float: left;">
            <input type="checkbox" id="useSecType"/>@Resources.Global.Sec_Type
            <select id="@secTypeSelectId" name="coption" class="medium2Select">
                @foreach (var o in HtmlUtil.CookOptions("bond_market_classify"))
                {
                    <option value="@o.ID">@o.Name</option>    
                }
            </select>
            <label>@Resources.Global.Report_Unit</label>
            <select id="@unitSelectId" name="unit" class="smallSelect">
                @foreach (var o in HtmlUtil.CookOptions("unit"))
                {
                    <option value="@o.ID">@o.Name</option>    
                }
            </select>
            
            <input type="button" id="_queryButtonId" value="@Resources.Global.Report_Query" onclick="GetIssueAmountReport(@Model.ID)"/>
        </div>
        <input type="hidden" id="issueAmountReportId" value="@Model.ID"/>
        <input type="hidden" id="issueAmountReportName" value="@Model.ReportName"/>
    </div>
</div>
<div id="@contentDivId" class="StatisticalContent" style="min-width:880px;">
    @Html.Partial("_IssueAmountReportContent", Model)
</div>
<script type="text/javascript">
    window.issueAmountReportUrl = '@issueAmountReportUrl';
    window.refreshBondDetailUrl = '@refreshBondDetailUrl';
    window.updateSubTypeOptionsUrl = '@updateSubTypeOptionsUrl';

    $(function () {
        $("#@datePickerId, #@endDatePickerId").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd'
        });

        refreshTopChart("@Model.ID", "@topChart");
        $("#ui-datepicker-div").css("border", "solid 1px black");

        $("#subTypeOptionSelect").multiselect({
            buttonMinWidth: 115,
            menuMinWidth: 240,
            checkAllText: '@Resources.Global.Select_All',
            uncheckAllText: '@Resources.Global.Unselect_All',
            noneSelectedText: '@Resources.Global.Tip_PleaseSelect',
            selectedText: '# @Resources.Global.Selected'
        });
    });

    function updateTopCharts() {
        refreshTopChart("@Model.ID", "@topChart");
    }

    function triggerTopChartsChange(id) {
        $("#topchart_ddl2_" + id).change();
    }

    function UpdateSubTypeOptions(reportId) {
        var type = $('#tselect' + reportId + ' option:selected').val();
        $.ajax({
            type: 'POST',
            url: window.updateSubTypeOptionsUrl,
            data: {
                type: type
            },
            success: function (data) {
                $("#subTypeOptionSelect").html(data);
                $("#subTypeOptionSelect").multiselect('refresh');
            },
            async: true
        });
    }
 </script>

web/VAV.Web/Views/BondReport/RateOfIssues.cshtml
@model VAV.Web.ViewModels.Bond.BondIssueRateReport
@using VAV.Web.Common;
@{
	Layout = null;
	var datePickerId = "datePicker" + @Model.ID;
	var endDatePickerId = "endDatePicker" + @Model.ID;
	var addButtonId = "add" + @Model.ID;
	var typeSelectId = "tselect" + @Model.ID;
	var termSelectId = "termSelect" + @Model.ID;
	var couponTypeSelectId = "couponTypeSelect" + @Model.ID;
	var ratingSelectId = "ratingSelect" + @Model.ID;
	var startDate = new DateTime(DateTime.Now.Year - 1, DateTime.Now.Month, 1).ToString("yyyy-MM-dd");

}
@using (Html.BeginForm("AddBond", "BondReport", FormMethod.Post, new { id = "add_bond" }))
{
	<div id="filterDiv" style="height:20px;min-width:1000px;" class="colorBlock">
		<input name="reportId" value="@Model.ID" style="display:none" />
		<input name="displayName" value="@Model.Name" style="display:none" />
		<div style="float: left;margin-left: 5px;">
			@Resources.Global.Report_Query_From
			<input type="text" name="date" id="@datePickerId" value="@startDate" class="dateInput" readonly="readonly"/>
		</div>
		<div style="float: left;margin-left: 5px;">
			<label style="margin-left: 3px;">@Resources.Global.Bond_CDC_Classify</label>
			<select id="@typeSelectId" name="bondType" class="largeSelect" style="width:220px;">
				@foreach (var o in HtmlUtil.CookOptions("bond_class"))
				{
					<option value="@o.ID">@o.Name</option>       
				}
			</select>
			<label style="margin-left: 3px;">@Resources.Global.Bond_Term</label>
			<select id="@termSelectId" name="term" class="mediumSelect">
				@foreach (var o in HtmlUtil.CookOptions("bond_term"))
				{
					<option value="@o.ID">@o.Name</option>   
				}
			</select>
			<label style="margin-left: 3px;">@Resources.Global.Bond_Coupon_class</label>
			<select id="@couponTypeSelectId" name="couponType" class="mediumSelect">
				<option value="n">@Resources.Global.Coupon_Type_Fixed</option>
				<option value="y">@Resources.Global.Coupon_Type_Float</option>
			</select>
			<label style="margin-left: 3px;">@Resources.Global.Bond_Rating</label>
			<select id="@ratingSelectId" name="rating" class="mediumSelect">
				<option value="All">@Resources.Global.Select_All</option>
				<option value="0">NR</option>
				<option value="1">AAA</option>
				<option value="2">AAA-</option>
				<option value="3">AA+</option>
				<option value="4">AA</option>
				<option value="5">AA-</option>
				<option value="6">A+</option>
				<option value="7">A</option>
				<option value="8">A-</option>
				<option value="9">A-1</option>
				<option value="10">A-2</option>
				<option value="11">BBB+</option>
				<option value="12">BBB</option>
				<option value="13">BBB-</option>
				<option value="14">BB+</option>
				<option value="15">BB</option>
				<option value="16">BB-</option>
				<option value="17">B+</option>
				<option value="18">B</option>
				<option value="19">B-</option>
				<option value="20">CCC+</option>
				<option value="21">CCC</option>
				<option value="22">CCC-</option>
				<option value="23">CC</option>
				<option value="24">C</option>
				<option value="25">D</option>
			</select>
			<input type="hidden" name="grid" />
		</div>
		<div style="float: left; margin-left: 5px;">
			<input type="button" id="@addButtonId" value="@Resources.Global.Bond_Add" onclick="submitForm()" style="width: 50px;" />
			<input type="hidden" id="reportId" />
		</div>
	</div>
}
<div id="issue_rates_statistical" style="height: 80%;min-width:932px;height:-webkit-calc(100% - 40px);">
	@Html.Partial("_IssueRatesStatistical", Model)
</div>

<script type="text/javascript">
	$(function () {
		$("#@datePickerId, #@endDatePickerId").datepicker({
			changeMonth: true,
			changeYear: true,
			dateFormat: 'yy-mm-dd'
		});
		var bondtabs = $("#bond_rate_tabs").tabs({
			create: function (event, ui) {
				var selectedTabTitle = $(ui.tab).find("a").text();
				$("#issue_rate_selected_grid").html(selectedTabTitle);
			},
			activate: function (event, ui) {
				var active = $("#bond_rate_tabs").tabs("option", "active");
				var selectedTabTitle = $("#bond_rate_tabs ul>li a").eq(active).text();
				$("#issue_rate_selected_grid").html(selectedTabTitle);
			}
		});
		bondtabs.delegate("span", "click", deleteProc);
	});

	function submitForm() {
		var frm = $('#add_bond').serialize();
		var value = $('#rate_grid').html();
		frm = frm + value;

		$("#issue_rates_statistical").block(
			{
				message: $('<img src="' + window.busyImageUrl + '" style="display: none;" />'),
				css: {
					top: ($("#issue_rates_statistical").height() - 54) / 2 + 'px',
					left: ($("#issue_rates_statistical").width() - 54) / 2 + 'px',
					width: '54px',
					height: '54px',
					border: '0px'
				},
				overlayCSS: { backgroundColor: '#272727', opacity: 1 }
			});
		setTimeout(
			$.ajax({
				url: '/BondReport/AddBond',
				type: 'POST',
				data: frm,
				beforeSend: function () {

				},
				onsuccess: function () {

				},
				success: function (result) {
					$("#issue_rates_statistical").html(result);
					var bondtabs = $("#bond_rate_tabs").tabs({
						create: function (event, ui) {
							var selectedTabTitle = $(ui.tab).find("a").text();
							$("#issue_rate_selected_grid").html(selectedTabTitle);
						},
						activate: function (event, ui) {
							var active = $("#bond_rate_tabs").tabs("option", "active");
							var selectedTabTitle = $("#bond_rate_tabs ul>li a").eq(active).text();
							$("#issue_rate_selected_grid").html(selectedTabTitle);
						}
					});
					bondtabs.delegate("span", "click", deleteProc);
					$("#issue_rates_statistical").unblock();

					if ($("#issue_rate_result").html() != "")
						showIssueRateResult();
				},
				error: function () { }
			}), 20);
	}

	function deleteProc() {
		var liId = $(this).closest("li").attr("id");
		var frm1 = $('#add_bond').serialize();
		var value1 = $('#rate_grid').html();
		frm1 = frm1 + value1;
		frm1 = "itemName=" + liId + "&" + frm1;
		$("#issue_rates_statistical").block(
			{
				message: $('<img src="' + window.busyImageUrl + '" style="display: none;" />'),
				css: {
					top: ($("#issue_rates_statistical").height() - 54) / 2 + 'px',
					left: ($("#issue_rates_statistical").width() - 54) / 2 + 'px',
					width: '54px',
					height: '54px',
					border: '0px'
				},
				overlayCSS: { backgroundColor: '#272727', opacity: 1 }
			});
		setTimeout(
			$.ajax({
				url: '/BondReport/DeleteBond',
				type: 'POST',
				data: frm1,
				beforeSend: function () {

				},
				onsuccess: function () {

				},
				success: function (result) {
					$("#issue_rates_statistical").html(result);
					var bondtabs = $("#bond_rate_tabs").tabs({
						create: function (event, ui) {
							var selectedTabTitle = $(ui.tab).find("a").text();
							$("#issue_rate_selected_grid").html(selectedTabTitle);
						},
						activate: function (event, ui) {
							var active = $("#bond_rate_tabs").tabs("option", "active");
							var selectedTabTitle = $("#bond_rate_tabs ul>li a").eq(active).text();
							$("#issue_rate_selected_grid").html(selectedTabTitle);
						}
					});

					bondtabs.delegate("span", "click", deleteProc);
					$("#issue_rates_statistical").unblock();
				},
				error: function () {
				}
			}), 0);
	}
	function showIssueRateResult() {
	    var h = 100, w = 200;
	    $("#issue_rate_result").dialog({
	        resizable: false,
	        height: h,
	        width: w,
	        modal: true,
	        close: function () {
	            $("#issue_rate_result").dialog("destroy");
	        }
	    });

	    $("#issue_rate_result").dialog("open");
	}

</script>