web/VAV.Web/ViewModels/OpenMarket/DetailDataReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VAV.Model.Data.OpenMarket;

namespace VAV.Web.ViewModels.OpenMarket
{
    public class DetailDataReportViewModel
    {

        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>
        public int ID { get; set; }

        /// <summary>
        /// The data that used in view
        /// </summary>
        public List<OpenMarketRepo> Content { get; set; }
    }
}

web/VAV.Web/ViewModels/OpenMarket/RatesAnalysisReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Script.Serialization;
using VAV.Model.Data;
using VAV.Web.Localization;
using VAV.Web.ViewModels.OpenMarket;
using VAV.Model.Data.OpenMarket;
using VAV.Web.ViewModels.Report;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Helpers;

namespace VAV.Web.ViewModels.OpenMarket
{
    /// <summary>
    /// Rates Analysis Report Model
    /// </summary>
    public class RatesAnalysisReportViewModel : BaseReportViewModel
    {
        public string ChartDisplayName { get; set; }
        public string GridDisplayName { get; set; }
        public string SelectTypeAndTerm { get; set; }
        public string ChartTheme { get; set; }

        public ChartModel Chart { get; set; }

        public string[] GridColumns;

        public List<OpenMarketRepo> GridData { get; set; }

        public bool IsStatisticalReport { get; set; }

        public bool IsInEnglish { get; private set; }

        public RatesAnalysisReportViewModel(int id, List<OpenMarketRepo> resultList,string theme):base(id)
        {
            this.IsInEnglish = CultureHelper.IsEnglishCulture();

            ID = id;
            GridDisplayName = IsInEnglish ? "Open Market -Rates Analysis" : "公开市场-利率走势分析";
            ChartDisplayName = IsInEnglish ? "Open Market - Rates Analysis Chart" : "公开市场-利率走势分析图表";
            ChartTheme = theme;
            var resultSet = (from gr in resultList.OrderBy(re=>re.Date)
                            group gr by gr.OperationType into grouped
                            select grouped).ToList();

            Dictionary<string, List<OpenMarketRepo>> groupedResultDict = new Dictionary<string, List<OpenMarketRepo>>();
            foreach (var item in resultSet)
            {
                var groupedResultSet = (from gr in item
                                 group gr by gr.OperationTerm into grouped
                                 select grouped).ToList();

                foreach (var grouped in groupedResultSet)
                {
                    groupedResultDict.Add(item.Key + " - " + grouped.Key, grouped.ToList());
                }
            }

            //GridData = resultList.Where(re => string.Compare(re.OperationType, selectedType, true) == 0 && string.Compare(re.OperationTerm, selectedTerm, true) == 0).ToList();
            GridData = groupedResultDict.FirstOrDefault().Value;
            SelectTypeAndTerm = groupedResultDict.FirstOrDefault().Key;
            Chart = InitialChart(groupedResultDict);
        }

        /// <summary>
        /// Initial chart
        /// </summary>
        /// <returns></returns>
        public ChartModel InitialChart(Dictionary<string, List<OpenMarketRepo>> groupedResultDict)
        {
            var series = new List<DotNet.Highcharts.Options.Series>();

            foreach (var item in groupedResultDict)
            {
                    var resultData = from re in item.Value select new object[] { ((DateTime)re.Date).AddDays(1), re.RefRate};
                    series.Add(new Series
                    {
                        Name = item.Key,
                        Data = new Data(resultData.ToArray())
                    });
            }

            //foreach (var groupByType in GridData.GroupBy(re => re.OperationType))
            //{
            //    foreach (var groupByTypeAndTerm in groupByType.GroupBy(re=>re.OperationTerm))
            //    {
            //        var resultList = groupByTypeAndTerm.Select(new OpenMarketRepo { });
            //        series.Add(new Series
            //        {
            //            Name = groupByTypeAndTerm.OperationType + " - " + groupByTypeAndTerm.OperationTerm,
            //            Data = new Data(new object[] { ((DateTime)groupByTypeAndTerm.Date).AddDays(1), groupByTypeAndTerm.RefRate })
            //        });
            //    }
            //}

            Chart = new ChartModel(Resources.Global.Source)
            {
                ChartName = "chart" + this.ID,
                Series = series.ToArray(),
                Title = ChartDisplayName,
                //TODO：global resource
                ChartType = ChartTypes.Line,
                IsXAxisDate = true,
                YAxisText = this.IsInEnglish ? "Yield(%)" : "收益率(%)",
                //TODO：global resource
                IsResizeable=true,
                ReportID = ID,
                Theme = ChartTheme
            };

            return Chart;
        }

        public override void Initialization()
        {
            throw new NotImplementedException();
        }
    }
}

web/VAV.Web/Controllers/OpenMarketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using VAV.DAL.Common;
using VAV.DAL.Services;
using VAV.Entities;
using VAV.Web.Localization;
using VAV.Web.ViewModels.OpenMarket;
using VAV.Model.Data;
using VAV.Model.Data.OpenMarket;
using VAV.Web.Common;
using VAV.Web.Extensions;
using VAV.DAL.Report;
using OpenMarketRepo = VAV.Model.Data.OpenMarket.OpenMarketRepo;

namespace VAV.Web.Controllers
{
    /// <summary>
    /// Open Market controller
    /// </summary>
    public class OpenMarketController : Controller
    {
        /// <summary>
        /// Report Generator
        /// </summary>
        [Dependency]
        public ReportService ReportService { get; set; }

        [Dependency]
        public OpenMarketReportRepository OpenMarketReportRepository { get; set; }

        /// <summary>
        /// _menuService
        /// </summary>
        [Dependency]
        public MenuService MenuService { get; set; }

        public DateTime DefaultStartDate
        {
            get { return new DateTime(DateTime.Now.Year - 1, DateTime.Now.Month, 1); }
        }

        [Localization]
        public ActionResult ExportOpenMarketDetailDataReport(int reportId, string type, string category, string startDate, string endDate, string unit, string includeExpired)
        {
            var openMarketRepo = ReportService.GetOpenMarketRepo(new DetailDataReportParams
            {
                StartDate = Convert.ToDateTime(startDate),
                EndDate = Convert.ToDateTime(endDate),
                Type = type,
                Group = category,
                Unit = unit,
                IncludeExpired = includeExpired == "true" ? true : false
            }, new GlobalValueParams
            {
                Type_CBankBill = Resources.Global.Type_CBankBill,
                Type_CBankBillIE = Resources.Global.Type_CBankBillIE,
                Type_Repo = Resources.Global.Type_Repo,
                Type_RepoIE = Resources.Global.Type_RepoIE,
                Type_ReverseRepo = Resources.Global.Type_ReverseRepo,
                Type_ReverseRepoIE = Resources.Global.Type_ReverseRepoIE,
                Type_FMD = Resources.Global.Type_Fmd,
                Type_FMDIE = Resources.Global.Type_FMDIE,
                Report_Expire = Resources.Global.Report_Expire,
                Direction_injection = Resources.Global.Direction_injection,
                Direction_withdrawal = Resources.Global.Direction_withdrawal,
                CurrentContext = Resources.Global.CurrentContext
            }).ToList();
            //tempFlag is refecenced to sign whether category is used
            int tempFlag = 0;
            var result = VAV.Web.Extensions.OpenMarketExtension.GetCategorys(openMarketRepo, category, ref tempFlag);

            string[] rowKeys = { "Date", "IssueDate", "Direction", "OperationType", "Code", "OperationTerm", "Volume", "Amount", "PirceRate", "MaturityDate", "RefRate" };
            string[] headers = { Resources.Global.Date, Resources.Global.Issue_Date, Resources.Global.Operation_Direction, Resources.Global.Operation_Type, Resources.Global.Code, Resources.Global.Option_Term, Resources.Global.Volume, Resources.Global.Amount, Resources.Global.Price_Rate, Resources.Global.Maturity_Date, Resources.Global.Ref_Rate };
            var rows = result;
            string reportName = MenuService.GetMenuNodeByReportId(reportId).DisplayName;

            string isSumRowColumnName = "IsSumItem";
            string sumGroupColumnName = "Category";

            return new ExcelResult(rows.AsQueryable(), headers, rowKeys, reportName, reportName, isSumRowColumnName: isSumRowColumnName, sumGroupColumnName: sumGroupColumnName);
        }

        private ImmaturityAmount GetImmaturityAmount(DateTime queryDate, string unit)
        {
            var table = OpenMarketReportRepository.GetImmaturityAmount(queryDate);
            var row = table.Rows[0];

            var amount = new ImmaturityAmount()
            {
                All = SwitchAmountUnit(unit, double.Parse(row["total"].ToString())),
                CBankBill = SwitchAmountUnit(unit,double.Parse(row["cbb"].ToString())),
                FMD = SwitchAmountUnit(unit, double.Parse(row["fmd"].ToString())),
                Repo = SwitchAmountUnit(unit, double.Parse(row["rp"].ToString())),
                ReverseRepo = SwitchAmountUnit(unit, double.Parse(row["rrp"].ToString())),
                Mlf = SwitchAmountUnit(unit, double.Parse(row["mlf"].ToString()))
            };
            return amount;
        }

        public double SwitchAmountUnit(string unit, double num)
        {
            int multiplier = 1;
            switch (unit)
            {
                case ConstValues.Unit_100M:
                    multiplier = 1;
                    break;
                case ConstValues.Unit_M:
                    multiplier = 100;
                    break;
                case ConstValues.Unit_10K:
                    multiplier = 10000;
                    break;
                case ConstValues.Unit_K:
                    multiplier = 100000;
                    break;
                default:
                    break;
            }
            return num * multiplier;
        }

        [Localization]
        public ActionResult GetMonetaryAndReturnReport(int id)
        {
            ReportInfo reportInfo = ReportService.GetReportInfoById(id);
            var openMarketRepo = ReportService.GetOpenMarketRepo(new DetailDataReportParams
            {
                StartDate = DefaultStartDate,
                EndDate = DateTime.Now,
                IncludeExpired = true,
                //Type = ConstValues.Type_All,
                Type = "CBB,RP,RRP,MLF",
                Unit = ConstValues.Unit_100M,
                Group = ""
            }, new GlobalValueParams
            {
                Type_CBankBill = Resources.Global.Type_CBankBill,
                Type_CBankBillIE = Resources.Global.Type_CBankBillIE,
                Type_Repo = Resources.Global.Type_Repo,
                Type_RepoIE = Resources.Global.Type_RepoIE,
                Type_ReverseRepo = Resources.Global.Type_ReverseRepo,
                Type_ReverseRepoIE = Resources.Global.Type_ReverseRepoIE,
                Type_FMD = Resources.Global.Type_Fmd,
                Type_FMDIE = Resources.Global.Type_FMDIE,
                Type_MLF =Resources.Global.Type_MLF,
                Type_MLFIE = Resources.Global.Type_MLFIE,
                Report_Expire = Resources.Global.Report_Expire,
                Direction_injection = Resources.Global.Direction_injection,
                Direction_withdrawal = Resources.Global.Direction_withdrawal,
                CurrentContext = Resources.Global.CurrentContext
            }).ToList();

            ViewData["Category" + reportInfo.ReportId] = ConstValues.Type_All;
            ViewData["Type" + reportInfo.ReportId] = "Week";
            ViewData["StartDate" + reportInfo.ReportId] = DefaultStartDate;
            ViewData["EndDate" + reportInfo.ReportId] = DateTime.Now;
            ViewData["Unit" + reportInfo.ReportId] = ConstValues.Unit_100M;
            ViewData["OperationType" + reportInfo.ReportId] = "ALL";
            var result = GetMonetaryAndReturnSummaryModel(DefaultStartDate, DateTime.Now, "Week", openMarketRepo);
            for (int i = result.Count - 1; i >= 0; i--)
            {
                //if (i == result.Count - 1) result[i].SumInjectionWithdrawal = result[i].NetInjectionWithdrawal;
                result[i].SumInjectionWithdrawal = i == result.Count - 1 ? result[i].NetInjectionWithdrawal : result[i + 1].SumInjectionWithdrawal + result[i].NetInjectionWithdrawal;
            }
            if (result.Count == 0)
            {
                return new EmptyResult();
            }
            return View("MonetaryAndReturnAnalysisReport", new MaRAnalysisReportViewModel(reportInfo.ReportId, result, result[0].OpenMarketRepoList, ThemeHelper.GetTheme(Request), GetImmaturityAmount(DateTime.Now, ConstValues.Unit_100M)));
        }

        [Localization]
        public ActionResult GetMonetaryAndReturnReportContent(int reportId, string type, string category, string startDate, string endDate, string unit, string operationType )
        {
            if (string.IsNullOrEmpty(startDate) || string.IsNullOrEmpty(endDate) || string.IsNullOrEmpty(type))
                return new EmptyResult();
            var startDateValue = DateTime.Parse(startDate);
            var endDateValue = DateTime.Parse(endDate);
            
            var openMarketRepo = ReportService.GetOpenMarketRepo(new DetailDataReportParams
            {
                StartDate = startDateValue,
                EndDate = endDateValue,
                Unit = unit,
                IncludeExpired = true,
                Type = operationType
            }, new GlobalValueParams
            {
                Type_CBankBill = Resources.Global.Type_CBankBill,
                Type_CBankBillIE = Resources.Global.Type_CBankBillIE,
                Type_Repo = Resources.Global.Type_Repo,
                Type_RepoIE = Resources.Global.Type_RepoIE,
                Type_ReverseRepo = Resources.Global.Type_ReverseRepo,
                Type_ReverseRepoIE = Resources.Global.Type_ReverseRepoIE,
                Type_FMD = Resources.Global.Type_Fmd,
                Type_FMDIE = Resources.Global.Type_FMDIE,
                Type_MLF = Resources.Global.Type_MLF,
                Type_MLFIE = Resources.Global.Type_MLFIE,
                Report_Expire = Resources.Global.Report_Expire,
                Direction_injection = Resources.Global.Direction_injection,
                Direction_withdrawal = Resources.Global.Direction_withdrawal,
                CurrentContext = Resources.Global.CurrentContext,
            }).ToList();
            ViewData["Type" + reportId] = type;

web/VAV.Web/Views/OpenMarket/MonetaryAndReturnAnalysisReport.cshtml
@using VAV.Web.Common;
@using VAV.Web.ViewModels.OpenMarket;

@model MaRAnalysisReportViewModel
@{
    Layout = null;
    var datePickerId = "datePicker" + @Model.ID;
    var endDatePickerId = "endDatePicker" + @Model.ID;
    var queryButtonId = "query" + @Model.ID;
    var contentDivId = "contentDiv" + @Model.ID;
    var frequencySelectId = "tselect" + @Model.ID;
    var unitSelectId = "uselect" + @Model.ID; 
    var startDate = new DateTime(DateTime.Now.Year - 1, DateTime.Now.Month, 1).ToString("yyyy-MM-dd");
    var endDate = DateTime.Now.ToString("yyyy-MM-dd");

    var news_asset = VAV.Web.Localization.CultureHelper.IsEnglishCulture() ? "CN/MMT" : "CN/MMTCN";
    var news_text = VAV.Web.Localization.CultureHelper.IsEnglishCulture() ? "News" : "新闻";
}
<div class="colorBlock" style="min-width:1000px;">
    <div id="filterDiv" style="margin: 5px 0px 0px 10px; height:27px;">
        <div style="float: left;">
            @Resources.Global.Report_Query_From
            <input type="text" id="@datePickerId" value="@startDate" class="dateInput" readonly/>
            @Resources.Global.Report_Query_End
            <input type="text" id="@endDatePickerId" value="@endDate" class="dateInput" readonly/>
        </div>
        <div style="float: left;">
            @Resources.Global.Frequency
            <select id="@frequencySelectId" name="type" class="medium2Select">
                @foreach (var o in HtmlUtil.CookOptions("summarizing_frequency"))
                {
                    <option value="@o.ID">@o.Name</option>
                }
            </select>
            @Resources.Global.Report_Type
            <select id="tselect_@Model.ID" name="tselect_@ViewBag.ID"  multiple="multiple">
                @foreach (var o in HtmlUtil.SelectOptions())
                {
                    <option selected="@o.Selected" value ="@o.Value">@o.Text</option>    
                }
            </select>
            @Resources.Global.Report_Unit
            <select id="@unitSelectId" name="unit" class="smallSelect">
                @foreach (var o in HtmlUtil.CookOptions("unit"))
                {
                    <option value ="@o.ID">@o.Name</option>    
                }
            </select>
        </div>
        <div style="float: left;">
            <input type="button" id="@queryButtonId" value="@Resources.Global.Report_Query" onclick="updateMonetaryAndReturnReport()"/>
            
            <input type="hidden" id="reportId" />
        </div>
        <a href="#">
            <img onclick="OpenNews()" title="@news_text" src="~/Content/themes/base/images/multimedianews.ico"
                    style="float: right; margin-right: 10px; margin-top: 7px" />
        </a>
    </div>
</div>
<div id="@contentDivId" style="position: absolute;height: 90%;width: 100%;height: -webkit-calc(100% - 42px);min-width:850px;">
    @Html.Partial("_MonetaryAndReturnAnalysisReportContent", Model)
</div>
<script type="text/javascript">

    function updateMonetaryAndReturnReport() {
        var operationType = $('#tselect_@Model.ID').val();
        if(operationType != null) operationType = operationType.join();
        AjaxWithBlock(
                    $('#@contentDivId'), 
                    "@Url.Action("GetMonetaryAndReturnReportContent", "OpenMarket")",
                    {
                        startDate: $("#@datePickerId").val(),
                        endDate: $("#@endDatePickerId").val(),
                        type: $("#@frequencySelectId").val(),
                        unit: $('#@unitSelectId').val(),
                        operationType : operationType,
                        reportId: @Model.ID
                    }, 
                    function (data) {
                        $("#@contentDivId").html(data);
                    }
            );
    }

    $(function () {
        $("#@datePickerId, #@endDatePickerId").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd'
        });
        $("#ui-datepicker-div").css("border", "solid 1px black");
        $("#tselect_@Model.ID").multiselect({
                buttonMinWidth: 115,
                menuMinWidth: 240,
                checkAllText: '@Resources.Global.Select_All',
                uncheckAllText: '@Resources.Global.Unselect_All',
                noneSelectedText: '@Resources.Global.Tip_PleaseSelect',
                selectedText: '# @Resources.Global.Selected'
            });
    });
    function OpenNews(){
        var data = {
            target: "popup",
            location: {
                x: 200,
                y: 100,
                width: 600,
                height: 400
            },
            name: "News",
            entities: [{
                "NewsQuery": "@news_asset"
            }]
        };
        JET.navigate(data);

    }
</script>

web/VAV.Web/Views/OpenMarket/_DetailDataReportTable.cshtml
@using VAV.Model.Data.OpenMarket;
@using VAV.Web.Extensions;
@model VAV.Web.ViewModels.OpenMarket.DetailDataReportViewModel
@{
    Layout = null;
    var exportType = @ViewData["Type" + Model.ID] == null ? "" : @ViewData["Type" + Model.ID].ToString();
    var exportCategory = @ViewData["Category" + Model.ID] == null ? "" : @ViewData["Category" + Model.ID].ToString();
    var exportStartDate = @ViewData["StartDate" + Model.ID] == null ? "" : @ViewData["StartDate" + Model.ID].ToString();
    var exportEndDate = @ViewData["EndDate" + Model.ID] == null ? "" : @ViewData["EndDate" + Model.ID].ToString();
    var exportUnit = @ViewData["Unit" + Model.ID] == null ? "" : @ViewData["Unit" + Model.ID].ToString();
    var exportIncludeExpired = @ViewData["IncludeExpired" + Model.ID] == null ? "" : @ViewData["IncludeExpired" + Model.ID].ToString();
}
<div>
    <input type="hidden" id="exportType_@Model.ID" value="@exportType"/>
    <input type="hidden" id="exportCategory_@Model.ID" value="@exportCategory"/>
    <input type="hidden" id="exportStartDate_@Model.ID"  value="@exportStartDate"/>
    <input type="hidden" id="exportEndDate_@Model.ID"  value="@exportEndDate"/>
    <input type="hidden" id="exportUnit_@Model.ID" value="@exportUnit"/>
    <input type="hidden" id="exportIncludeExpired_@Model.ID" value="@exportIncludeExpired"/>
</div>
<table id="tableOpenMarket" class="datatable">
    <thead>
        <tr class="hr">
            <th align="center">
                @Resources.Global.Issue_Date
            </th>
            <th align="center">
                @Resources.Global.Operation_Direction
            </th>
            <th align="center">
                @Resources.Global.Operation_Type
            </th>
            <th align="center">
                @Resources.Global.Code
            </th>
            <th align="center">
                @Resources.Global.Option_Term
            </th>
            <th align="center">
                @Resources.Global.Volume
            </th>
            <th align="center">
                @Resources.Global.Amount
            </th>
            <th align="center">
                @Resources.Global.Price_Rate
            </th>
            <th align="center">
                @Resources.Global.Maturity_Date
            </th>
            <th align="center">
                @Resources.Global.Ref_Rate
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Content.Count() > 0)
        {
            string categoryType = ViewData["Category" + @Model.ID] == null ? string.Empty : ViewData["Category" + @Model.ID].ToString();
            int flag = 0;
            List<OpenMarketRepo> selectedGroupRepo = OpenMarketExtension.GetCategorys(Model.Content, categoryType, ref flag);
            OpenMarketRepo sumItem = new OpenMarketRepo();
            string trName = "";
            int category = 0;
            foreach (var r in selectedGroupRepo)
            {
                if (r.IsSumItem)
                {
                    category++;
                    sumItem = r;
                    trName = "OpenMarketCategory" + category.ToString();
                    <tr id="@trName">
                        @if (sumItem.Category == Resources.Global.Total)
                        {
                            <td style="text-align: left">@sumItem.Category
                            </td>
                        }
                        else
                        {
                            <td>
                                <div  class="expand" onclick="ShowOrHide('@trName',this)" style ="float:left">
                                </div>
                                <div style="text-align: left">
                                    @sumItem.Category
                                </div>
                            </td>
                        }
                        <td align="left" style="text-align: left">
                        </td>
                        <td style="text-align: left">
                        </td>
                        <td style="text-align: left">
                        </td>
                        <td style="text-align: left">
                        </td>
                        <td align="right">@string.Format("{0:N2}", sumItem.Volume)
                        </td>
                        <td align="right">@string.Format("{0:N2}", sumItem.Amount)
                        </td>
                        <td align="right">
                        </td>
                        <td style="text-align: left">
                        </td>
                        <td align="right">
                        </td>
                    </tr>
                }
                else
                {
                    <tr class="@trName">
                        <td style="text-align: left">@Convert.ToDateTime(r.IssueDate.ToString()).ToString("yyyy-MM-dd")
                        </td>
                        <td style="text-align: left">@r.Direction
                        </td>
                        <td style="text-align: left">@r.OperationType
                        </td>
                        <td  style="text-align:left" class="readTimeTD" onclick="TurnToLink('@r.Category','@r.AssetId','@Model.ID')">
                            <a href="javascript:void(0)" class="realTime" title="View real-time"></a>@r.Code
                        </td>
                        <td style="text-align: left">@r.OperationTerm
                        </td>
                        <td align="right">@string.Format("{0:N2}", r.Volume)
                        </td>
                        <td align="right">@string.Format("{0:N2}", r.Amount)
                        </td>
                        <td align="right">@r.PirceRate
                        </td>
                        <td style="text-align: left">@Convert.ToDateTime(r.MaturityDate.ToString()).ToString("yyyy-MM-dd")
                        </td>
                        <td align="right">@r.RefRate
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>
<div>@Resources.Global.Source</div>
<script type="text/javascript">
    function ShowOrHide(className, img) {
        if ($(img).attr("class") == "expand")
            $(img).toggleClass('expand close');
        else
            $(img).toggleClass('close expand');

        $("." + className).toggle();
    }
    $(function () {
        DrawBackgroundColor();
    });
    function DrawBackgroundColor() {
        $("#tableOpenMarket tbody tr:even").addClass('row-e');
        $("#tableOpenMarket tbody tr:odd").addClass('row-o');
    }
    function TurnToLink(category, asset_id, repoId) {
        if (asset_id.indexOf('=') == -1){
            assetid = "cpurl://views.cp./Explorer/Default.aspx?s=0x";
            assetid = assetid + asset_id + "&st=EJVAssetID";
            window.open(assetid);
        }
        else {
            var data = {
                target: "popup",
                location: {
                    x: 200,
                    y: 100,
                    width: 600,
                    height: 400
                },
                name: "Quote Object",
                entities: [{
                    type: "COMP",
                    "RIC": asset_id
                }]
            };
            JET.navigate(data);
        }
    }
    
</script>