web/VAV.Web/ViewModels/ResearchReport/ReportSearchViewModel.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using VAV.Web.ViewModels.Report;
using Microsoft.Practices.Unity;
using VAV.DAL.ResearchReport;
using VAV.Entities;
using System.IO;


namespace VAV.Web.ViewModels.ResearchReport
{
    public class ReportSearchViewModel : BaseReportViewModel
    {

        //[Dependency]
        private ResearchReportRepository _repository { get; set; }

        public ReportSearchViewModel(int id, string user)
            : base(id, user)
        {
            _repository = (ResearchReportRepository)DependencyResolver.Current.GetService(typeof(ResearchReportRepository));
        }

        public override void Initialization()
        {
           
        }
    }
}

web/VAV.Web/ViewModels/ResearchReport/ResearchReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Web;
using System.Web.Mvc;
using VAV.DAL.Common;
using VAV.Web.ViewModels.Report;
using VAV.DAL.ResearchReport;
using VAV.Entities;
using System.IO;
using System.Linq;


namespace VAV.Web.ViewModels.ResearchReport
{
    public class ResearchReportViewModel : BaseReportViewModel
    {
        //[Dependency]
        private ResearchReportRepository _repository { get; set; }

        public List<INSTITUTIONINFO> INSTITUTIONINFO { get; set; }
        public List<InstitutionViewModel> InstitList { get; set; }
        public IList<string> fileTypeList = new List<string>();

        public ResearchReportViewModel(int id, string user)
            : base(id, user)
        {
            _repository = (ResearchReportRepository)DependencyResolver.Current.GetService(typeof(ResearchReportRepository));
        }

        public override void Initialization()
        {
            var strWhere = "";
            if (ID == 55) //Fx market
            {
                strWhere = "WHERE num<=5 AND BusinessCodeType='FX' ";
            }
            else if (ID == 61) // Fi market
            {
                strWhere += "WHERE num<=5 AND BusinessCodeType IN('FI','MM') ";
            }
            else if (ID == 22003)
            {
                strWhere = "WHERE num<=5 AND BusinessCodeType IN('Agriculture','Energy','Commodities','Metal','Others') ";
            }
            var oracleDBHelper =
                new OracleDBHelper(ConfigurationManager.AppSettings["FileDBConStr"]);
            var sql = "select * FROM GETReseachReportByType " + strWhere +
                      "ORDER BY InstitutionOrder,Code,TypeOrder,fileTypeCTIME,ReportDate DESC,num";
            var dt = oracleDBHelper.GetDataTableBySql(sql);
            //var cmd = new OracleCommand
            //{
            //    Connection = (OracleConnection)(db.Database.Connection),
            //    CommandText = "select * FROM GETReseachReportByType " + strWhere +
            //                  "ORDER BY InstitutionOrder,Code,TypeOrder,fileTypeCTIME,ReportDate DESC,num"
            //};
            //var da = new OracleDataAdapter(cmd);
            //da.Fill(dt);
            InstitList = (from DataRow dr in dt.Rows
                          select new InstitutionViewModel
                          {
                              Code = dr["Code"].ToString(),
                              InstitutionNameCn = dr["InstitutionNameCn"].ToString(),
                              InstitutionNameEn = dr["InstitutionNameEn"].ToString(),
                              Mtime = Convert.ToDateTime(dr["MTIME"]),
                              InstitutionExtension = dr["InstitutionExtension"].ToString(),
                              FileTypeNameCn = dr["FileTypeNameCn"].ToString(),
                              FileTypeNameEn = dr["FileTypeNameEn"].ToString(),
                              FileNameCn = dr["FileNameCn"].ToString(),
                              FileNameEn = dr["FileNameEn"].ToString(),
                              FileId = Convert.ToInt32(dr["FileId"]),
                              Extension = dr["Extension"].ToString(),
                              ReportDate = Convert.ToDateTime(dr["ReportDate"]),
                          }).ToList();
            INSTITUTIONINFO = (from m in InstitList.Select(re => new { re.InstitutionNameCn, re.InstitutionNameEn, re.Mtime, re.Code, Extension = re.InstitutionExtension }).Distinct()
                               select new INSTITUTIONINFO { INSTITUTIONNAMECN = m.InstitutionNameCn, INSTITUTIONNAMEEN = m.InstitutionNameEn, MTIME = m.Mtime, CODE = m.Code, EXTENSION = m.Extension }).Distinct().ToList();
            foreach (var inst in INSTITUTIONINFO)
            {
                inst.LogoPath = GetLogoImagePath(inst);
            }
        }

        private string GetLogoImagePath(INSTITUTIONINFO inst)
        {
            if (string.IsNullOrEmpty(inst.EXTENSION))
                return "";
            var path = string.Format("{0}logo-{1}-{2}.{3}", "~/Cache/", inst.CODE, inst.MTIME.Value.ToFileTime(), inst.EXTENSION);
            var realPath = HttpContext.Current.Server.MapPath(path);
            if (!File.Exists(realPath))
            {
                byte[] buffer = _repository.GetInstLogoBytesByCode(inst.CODE);
                if (buffer == null)
                    return "";
                using (var fs = new FileStream(realPath, FileMode.Create))
                {
                    fs.Write(buffer, 0, buffer.Length);
                }

            }
            return VirtualPathUtility.ToAbsolute(path);
        }
    }
}

web/VAV.Web/Controllers/ResearchReportController.cs
using System.IO;
using System.Web.Mvc;
using log4net;
using VAV.DAL.ResearchReport;
using Microsoft.Practices.Unity;
using VAV.Web.Common;
using VAV.Web.Localization;
using System;


namespace VAV.Web.Controllers
{
    public class ResearchReportController : BaseController
    {
        [Dependency]
        public ResearchReportRepository _repository { get; set; }

        private readonly ILog _log = LogManager.GetLogger(typeof(ResearchReportController));
        [Localization]
        public ActionResult DownloadFile(int id)
        {
            //_log.Error("Start:" + id);
            var file = _repository.GetFileDataById(id);
            //_log.Error("Get FileData:" + id);
            var fileDetail = _repository.GetFileDetailById(id);
            //_log.Error("Get FileDetail Success:" + id);
            if (file == null)
                return HttpNotFound();
            //_log.Error("Start Get Mime：" + id);
            //var contentType = MimeHelper.GetMimeTypeByExt(fileDetail.EXTENSION);
            var contentType = MimeHelper.GetMimeTypeByExt(fileDetail.EXTENSION.ToLower());
            //_log.Error("Success Get Mime：" + contentType);
            //_log.Error("Start DownLoad:" + id);
            var ms = new MemoryStream(file.Content);
            return File(ms, contentType, Resources.Global.DownloadFileName + "." + fileDetail.EXTENSION);
        }

        [Localization]
        public string UpdateRsReportTypeOption(string orgCodes)
        {
            var options = HtmlUtil.GetRsReportTypeOptionHtml(orgCodes);
            return options;
        }

        public string GeResUrl(int id)
        {
            _log.Error("Start GeResUrl：" + id);
            _repository.AddFileVisitLog(id, UserSettingHelper.GetUserId(Request));
            var fileDetail = _repository.GetFileDetailById(id);
            string instiu = fileDetail.INSTITUTIONINFOCODE;
            string result = string.Empty;
            _log.Error("Get fileDetail.EXTENSION：" + fileDetail.EXTENSION);
            if (fileDetail.EXTENSION == "pdf" && "NationalGrainAndOilsInformationCenter,BeijingZhongdianJingwei".Contains(instiu))
                result = "/PdfView/PdfView?did="+id ;
            else
                result = "/ResearchReport/DownloadFile?id=" + id ;
            return result;

        }
        [Localization]
        public ActionResult GeRSReport(DateTime startDate, DateTime endDate, string orgCodes, string reportTypes, string reportName, int pageNo, int pageSize, bool isHTML = false)
        {
            int total;
            var reports = _repository.GetRSReport(startDate, endDate, orgCodes, reportTypes, reportName, pageNo, pageSize, out total);
            var result = new
            {
                Data = reports,
                Total = total,
                CurrentPage = pageNo,
                PageSize = pageSize
            };
            return isHTML ? Json(result, "text/html", JsonRequestBehavior.AllowGet) : Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

web/VAV.Web/Views/ResearchReport/PdfViewer.cshtml
@model List<string>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title></title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    <style type="text/css">
        .jssora03l, .jssora03r, .jssora03ldn, .jssora03rdn
        {
            position: absolute;
            cursor: pointer;
            display: block;
            background: url(/Content/images/a02.png) no-repeat;
            overflow: hidden;
        }
        .jssora03l
        {
            background-position: -3px -33px;
        }
        .jssora03r
        {
            background-position: -63px -33px;
        }
        .jssora03l:hover
        {
            background-position: -123px -33px;
        }
        .jssora03r:hover
        {
            background-position: -183px -33px;
        }
        .jssora03ldn
        {
            background-position: -243px -33px;
        }
        .jssora03rdn
        {
            background-position: -303px -33px;
        }
    </style>
    <script type="text/javascript">
        function AutoResizeImage(maxWidth, maxHeight, objImg) {
            var img = new Image();
            img.src = objImg.src;
            var hRatio;
            var wRatio;
            var Ratio = 1;
            var w = img.width;
            var h = img.height;
            wRatio = maxWidth / w;
            hRatio = maxHeight / h;
            if (maxWidth == 0 && maxHeight == 0) {
                Ratio = 1;
            } else if (maxWidth == 0) {//
                if (hRatio < 1) Ratio = hRatio;
            } else if (maxHeight == 0) {
                if (wRatio < 1) Ratio = wRatio;
            } else if (wRatio < 1 || hRatio < 1) {
                Ratio = (wRatio <= hRatio ? wRatio : hRatio);
            }
            if (Ratio < 1) {
                w = w * Ratio;
                h = h * Ratio;
            }
            objImg.height = h;
            objImg.width = w;
        }
        function JustifyPic() {
            var w = $(this).width();
            var h = $(this).height();
            $("#slide[debug-id=slide-board]").css("top", (h - $("#slide[debug-id=slide-board]").height()) / 2 + 'px');
            $("#slide[debug-id=slide-board]").css("left", (w - $("#slide[debug-id=slide-board]").width()) / 2 + 'px');
            $("span").parent().width(w + 'px');
            $("span").parent().height(h + 'px');
        }
        jQuery(document).ready(function ($) {
            //JustifyPic();
            var options = {
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $ArrowNavigatorOptions: {                       //[Optional] Options to specify and enable arrow navigator or not
                    $Class: $JssorArrowNavigator$,              //[Requried] Class to create arrow navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 0,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                }
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);
            $(window).resize(function () {
                //JustifyPic();
            })
        });
    </script>
</head>
<body >
  @*  <div id="slider1_container" style="position: relative; top: 0px; left: 0px;width:1050px;height:1500px">
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width:1050px;height:1500px; overflow: hidden;" id="slide">*@
            @{
                foreach (var img in Model)
                {
              @*  <div>*@
                    <img  src="@img&id=1"   alt=''  style="width:100%;"/>
                     
                <hr />
               @* </div>*@
           
                }
            }
      @*  </div>
        <span u="arrowleft" class="jssora03l" style="width: 55px; height: 55px; top: 350px;
            left: 0px;"></span>
        <span u="arrowright" class="jssora03r" style="width: 55px; height: 55px; top: 350px;
            right: 0px"></span>
      
    </div>*@
</body>
</html>

web/VAV.Web/Views/ResearchReport/ReportSearch.cshtml
@model VAV.Web.ViewModels.ResearchReport.ReportSearchViewModel
@using VAV.Web.Common
@{
    var datePickerId = "datePicker" + @Model.ID;
    var endDatePickerId = "endDatePicker" + @Model.ID;

    var startDate = DateTime.Now.AddYears(-1).ToString("yyyy-MM-dd");
    var endDate = DateTime.Now.ToString("yyyy-MM-dd");

    var contentDivId = "contentDiv" + @Model.ID;
    var queryButtonId = "query" + Model.ID;
    var tableId = "rsReporttable" + Model.ID;
    var reportName = Model.Name;
    var pageSize = 50;
    var productNameId = "productName" + @Model.ID;
    var updateRsReportTypeOptionUrl = VirtualPathUtility.ToAbsolute("~/ResearchReport/UpdateRsReportTypeOption");
    var refreshUrl = VirtualPathUtility.ToAbsolute("~/ResearchReport/GeRSReport");
    var downloadUrl = VirtualPathUtility.ToAbsolute("~/ResearchReport/DownloadFile");

    var org = @Request.QueryString["orgCode"] ?? "all";
    var fileType = @Request.QueryString["fileType"] ?? "all";
}
<div class="colorBlock" style="min-width: 1000px;">
    <div id="filterDiv" style="margin: 5px 0px 0px 10px; height: 27px;">
        <div style="float: left;">
            @Resources.Global.BankWMP_Research_StartDate
            <input type="text" id="@datePickerId" value="@startDate" class="dateInput" readonly/>
            <label style="margin-left: 10px;">@Resources.Global.BankWMP_Research_EndDate</label>
            <input type="text" id="@endDatePickerId" value="@endDate" class="dateInput" readonly/>
            <label>@Resources.Global.RS_Orgnization</label>
            @Html.DropDownList("rsReportOrg", HtmlUtil.GetOrgOptions(org), new { @class = "largeSelect", multiple = "multiple" })
            <label>@Resources.Global.BankWMP_Research_ReportType</label>
            @Html.DropDownList("rsReportType", HtmlUtil.GetReportTypeOptions(org, fileType).Where(t => t.Value != "Agriculture Daily"), new { @class = "largeSelect", multiple = "multiple" })
            <label>@Resources.Global.RS_ReportTitle</label>
            @Html.TextBox(@productNameId, "", new { @class = "text", @style = "width:118px;" })
            <input id="@queryButtonId" onclick="RS.UpdateReportData(1);" type="button" value="@Resources.Global.Report_Query" />
            <a onclick="window.open('cpurl://views.cp./Explorer/EVzResearchxAdvancedSearch.aspx')" href="javascript:void(0);" class="search" title="@Resources.Global.ReportSearch">
                &nbsp;</a>
        </div>
    </div>
</div>
<div id="@contentDivId" class="colorBlock" style="height: 91%; height: -webkit-calc(100% - 49px); min-width: 1000px;">
    <div class="colorBlock-header">
        <span class="colorBlock-header-span">@Resources.Global.BankWMP_Research_Title</span>
    </div>
    <div id="emptyMessage@(Model.ID)" style="display:none; margin-left:10px;">@Resources.Global.Empty_Result</div>
    <div id="pager@(Model.ID)">
        <div id="rsPaginateLabel@(Model.ID)" class="paginateOfLable">
            1 of 100</div>
        <div style="width: 300px; float: right; padding-right: 80px">
            <div id="rsPaginate@(Model.ID)">
            </div>
        </div>
        <div style="clear: both">
        </div>
    </div>
    <div class="ui-layout-pane" style="height: 90%; height: -webkit-calc(100% - 57px);
        min-width: 328px; overflow: auto">
        <table id="@tableId" class="datatable Zebra" style="cursor: pointer;">
            <thead>
                <tr class="hr">
                    <th>
                        @Resources.Global.RS_ReportTitle
                    </th>
                    <th>
                        @Resources.Global.BankWMP_Research_ReportDate
                    </th>
                    <th>
                        @Resources.Global.BankWMP_Research_ReportType
                    </th>
                    <th>
                        @Resources.Global.RS_Orgnization
                    </th>
                    <th>
                        @Resources.Global.BankWMP_Research_ReportAuthor
                    </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <input id="lastSelected" type="hidden" value="" />
        <div>@Resources.Global.Source</div>
    </div>
</div>
<script type="text/javascript">
var RS = (function (my) {
    function UpdatePaginationLabel(current,pageSize,total, id) {
        var start = (current - 1) * pageSize + 1;
        var end = current * pageSize;
        if(end > total) end = total;
            $(id).html(start + '-' + end + '@Resources.Global.WMP_of' + total);
    }

    my.BuildReportTable = function(data) {
        var markup = '<tr>'
                + '<td class="readTimeTD"><a href="#" ext="${Ext}" class="link" onclick="RS.DownloadFile(this, ${FileId})">${DisplayName}</a></td>'
                + '<td class="textLeft">${DisplayDate}</td>' 
                + '<td class="textLeft">${FileType}</td>'
                + '<td class="textLeft">${InstitutionName}</td>'
                + '<td class="textLeft">${Author}</td>'
                + '</tr>';
        $.template("rowTemplate", markup);
        $('#@tableId tbody').empty();
        $.tmpl("rowTemplate", data).appendTo("#@tableId tbody");
    };

    my.UpdateReportData = function(currentPage) {
        debugger;
            var org = $('#rsReportOrg').val();
            if (org != null) {
                org = org.join();
                org = ',' + org + ',';
            }

            var type = $('#rsReportType').val();
            if (type != null) {
                type = type.join();
                type = ',' + type + ',';
            }

            
            AjaxWithBlock($('#@contentDivId').parent(), "@refreshUrl",
            {
                startDate: $("#@datePickerId").val(),
                endDate: $("#@endDatePickerId").val(),
                orgCodes: org,
                reportTypes: type,
                reportName: $("#@productNameId").val(),
                pageNo: currentPage,
                pageSize: @pageSize,
                isHTML: false
            }, function (data) {
                    if (data.Total == 0) {
                    $("#pager@(Model.ID)").hide();
                    $("#@tableId").hide();
                }
                else {
                    $("#pager@(Model.ID)").show();
                    $("#@tableId").show();
                    RS.BuildReportTable(data.Data);
                    RS.UpdateReportPagination(data, "#rsPaginate@(Model.ID)");
                }
            });
    };

    my.DownloadFile = function(link, reportId) { 
       $.get("/ResearchReport/GeResUrl?id="+reportId,function (data){
        if(data.indexOf('DownloadFile')>0){
          window.location .href=data;
        }else {
         window.open(data,new Date(),'toolbar=no,menubar=no,scrollbars=no,resizable=no,location=no,status=no,width=800px,height=780px,left=300px,top=150px');
        }
         
       });
        $(link).css("color", "#ff8000");
    };
    
    my.UpdateReportPagination = function(data, id) {
        UpdatePaginationLabel(data.CurrentPage, 50, data.Total, "#rsPaginateLabel@(Model.ID)");
        $(id).paginate({
            count: Math.ceil(data.Total/50),
            start: data.CurrentPage,
            display: 50,
            border: false,
            text_color: '#00B3E3',
            background_color: 'none',
            text_hover_color: '#28D2FF',
            background_hover_color: 'none',
            images: false,
            mouse: 'press',
            onChange: function (page) {
                RS.UpdateReportData(page);
            },
            firstText:'@Resources.Global.Paginate_First',
            lastText:'@Resources.Global.Paginate_Last'
        });
     };

     my.UpdateRSTypeOption = function () {
        var org = $('#rsReportOrg').val();
        if (org != null) org = org.join();

        var lastSelected = $("#lastSelected").val();
        if (lastSelected == org)
            return;

        $("#lastSelected").val(org);
        
        $.ajax({
            type: 'POST',
            url: window.updateRsReportTypeOptionUrl,
            data: {
                orgCodes: org
            },
            success: function (data) {
                var op='<option value=\'Agriculture Daily\' selected >农业 日报</option>';
                var i=data .indexOf(op)!=-1?op.length:0;
                data =data.substring(i);
                $("#rsReportType").html(data);
                $("#rsReportType").multiselect('refresh');
            },
            async: true
        });
    };

    return my;
} (RS || {}));

$(function () {
    window.updateRsReportTypeOptionUrl = '@updateRsReportTypeOptionUrl';

    $("#@datePickerId, #@endDatePickerId").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd'
    });

    $("#rsReportOrg").multiselect({
        buttonMinWidth: 115,
        menuMinWidth: 240,
        checkAllText: '@Resources.Global.Select_All',
        uncheckAllText: '@Resources.Global.Unselect_All',
        noneSelectedText: '@Resources.Global.Tip_PleaseSelect',
        selectedText: '#@Resources.Global.Selected',
        close: function () {
            RS.UpdateRSTypeOption();
        }
    });

    $("#rsReportType").multiselect({
        buttonMinWidth: 115,
        menuMinWidth: 240,
        checkAllText: '@Resources.Global.Select_All',
        uncheckAllText: '@Resources.Global.Unselect_All',
        noneSelectedText: '@Resources.Global.Tip_PleaseSelect',
        selectedText: '#@Resources.Global.Selected'
    });

    //set initial value of last selected
    var org = $('#rsReportOrg').val();
    if (org != null) org = org.join();
    $("#lastSelected").val(org);

    var data = @{ Html.RenderAction("GeRSReport", "ResearchReport",
                                    new
                                    {
                                        startDate = @startDate,
                                        endDate = @endDate,
                                        orgCodes = @org,
                                        reportTypes = @fileType,
                                        reportName = "",
                                        pageNo = 1,
                                        pageSize = 50,
                                        isHTML = true
                                    });
                    };

     if (data.Total == 0) {
        $("#pager@(Model.ID)").hide();
        $("#@tableId").hide();
    }
    else {
        $("#pager@(Model.ID)").show();
        $("#@tableId").show();
        RS.BuildReportTable(data.Data);
        RS.UpdateReportPagination(data, "#rsPaginate@(Model.ID)");
    }
});      

</script>

web/VAV.Web/Views/ResearchReport/ResearchReport.cshtml
@model VAV.Web.ViewModels.ResearchReport.ResearchReportViewModel
@using VAV.Web.Common

<div class="colorBlock" style="height: 99%; height: -webkit-calc(100%-8px);">
    <div class="colorBlock-header">
        <span class="colorBlock-header-span">@Model.Name</span>
    </div>
    <div class="ui-layout-pane" style="height: 91%; height: -webkit-calc(100% - 30px);
        min-width: 328px; overflow: auto">
        @foreach (var inst in Model.INSTITUTIONINFO)
        {
            <div class="selistCredit">
                <div class="listh">
                    <span>
                        <img width="300" height="36" src="@inst.LogoPath" alt="@inst.DisplayName" title="@inst.DisplayName"/>
                    </span>
                </div>
                <div class="altFlexibleContainer listaset ">
                    <table class="selistinfo">
                         @foreach (var ftype in Model.InstitList.Where(re=>re.Code==inst.CODE).Select(g => new { g.FileTypeDisplayName,g.FileTypeNameEn }).Distinct())
                        {
                            <tr>
                                <th>
                                    <b>@ftype.FileTypeDisplayName</b>
                                    <a class="link" style="float:right;" href="#" onclick="RS.GoToReportSearch(',@(inst.CODE),', ',@(ftype.FileTypeNameEn),')">@Resources.Global.Common_More</a>
                                </th>
                            </tr>
                            foreach (var file in Model.InstitList.Where(re => re.Code == inst.CODE&&re.FileTypeNameEn==ftype.FileTypeNameEn).OrderByDescending(re=>re.ReportDate))
                            {
                            <tr>
                                <td>
                                    @(file.ReportDate.HasValue ? file.ReportDate.Value.ToString("yyyy-MM-dd") : "")
                                    &nbsp;&nbsp; <a class="link"  href="#" title="@file.FileDisplayName" onclick="RS.DownloadFile(this,@file.FileId,'@file.Extension')">
                                        @HtmlUtil.Truncate(file.FileDisplayName, 24)</a>
                                </td>
                            </tr>
                            }
                        }
                    </table>
                </div>
                <div style="clear: both;">
                </div>
            </div>

        }</div>
</div>

<script type="text/javascript">
    var RS = (function (my) {

        my.GoToReportSearch = function (orgCode, reportType) {
            CloseReport(62);
            OpenReport('62', '@Resources.Global.RS_ReportSearch', 'Research Report Search', '', '', { orgCode: orgCode, fileType: reportType });
        };
        my.DownloadFile = function (dom,fileID,ext) {
            $.get("/ResearchReport/GeResUrl?id=" + fileID, function (data) {
                if (data.indexOf('DownloadFile') > 0) {
                    window.location.href = data;
                } else {
                    window.open(data, new Date(), 'toolbar=no,menubar=no,scrollbars=no,resizable=no,location=no,status=no,width=800px,height=780px,left=300px,top=150px');
                }

            });
            $(dom).css("color", "#ff8000");
        };

        return my;
    } (RS || {}));
</script>