web/VAV.Web/ViewModels/IPP/File.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;


namespace VAV.Web.ViewModels.IPP
{
    public class IPPFile
    {
        private string reportDate;

        public long? Id { get; set; }

        public int Status { get; set; }

        public byte[] Doc { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "IPP_Title_Cn_Val")]
        [StringLength(100, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "TitleCnLengthMessage")]
        public string TitleCn { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "IPP_Title_En_Val")]
        [StringLength(100, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "TitleEnLengthMessage")]
        public string TitleEn { get; set; }

        public string Module { get; set; }

        public string Topic { get; set; }

        public string DescriptionCn { get; set; }

        public string DescriptionEn { get; set; }

        public string UploadType { get; set; }

        public string FileType { get; set; }

        public string WebsiteRic { get; set; }

        public string EikonRic { get; set; }

        public string ReportDate { 
            get
            {
                return reportDate;
            }
            set
            {
                reportDate = value;
            }
        }

        [StringLength(50, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "AuthorLengthMessage")]
        public string Author { get; set; }

        [StringLength(100, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "AuthorRMLengthMessage")]
        public string AuthorRM { get; set; }

        [RegularExpression(".+@.+\\..+", ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "EmailAddressValidation")]
        public string AuthorEmail { get; set; }

        [StringLength(50, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "SubmiterLengthMessage")]
        public string Submiter { get; set; }

        [StringLength(50, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "TagLengthMessage")]
        public string Tag { get; set; }

        public string SubmitterID { get; set; }

        public string SubmiterRM { get; set; }

        public string SubmiterName { get; set; }

        public List<SelectListItem> ModuleItems { get; set; }

        public List<SelectListItem> TopicItems { get; set; }

        public List<SelectListItem> UploadTypeItems { get; set; }

        public List<SelectListItem> RicTypeItems { get; set; }

        public string Source { get; set; }

        public string PreviousRequest { get; set; }

        public string FileName { get; set; }

        public int DisplayOrder { get; set; }

        public bool IsSetTop
        {
            get { return DisplayOrder == 1; }
            set { DisplayOrder = value ? 1 : 10000; }
        }
    }
}

web/VAV.Web/ViewModels/IPP/Topic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;


namespace VAV.Web.ViewModels.IPP
{
    public class IPPTopic
    {
        public int ID { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "IPP_Title_Cn_Val")]
        [StringLength(100, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "TitleCnLengthMessage")]
        public string NameCn { get; set;    }

        [Required(ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "IPP_Title_En_Val")]
        [StringLength(100, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "TitleEnLengthMessage")]
        public string NameEn { get; set; }

        public byte[] Thumbnail { get; set; }

        public string DescriptionCn { get; set; }

        public string DescriptionEn { get; set; }

        public bool IsApprove { get; set; }

        public bool IsInternalApprove { get; set; }

        public bool IsDirectDelete { get; set; }

        public string Creater { get; set; }

        [StringLength(50, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "TagLengthMessage")]
        public string Tag { get; set; }

        [StringLength(500, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "ApproverLengthMessage")]
        public string Approver { get; set; }

        [StringLength(100, ErrorMessageResourceType = typeof(Resources.IPP), ErrorMessageResourceName = "RMLinkLengthMessage")]
        public string RMLink { get; set; }

        public string ModuleID { get; set; }

        public string ImageName { get; set; }

        public List<SelectListItem> ModuleItems { get; set; }
    }
}

web/VAV.Web/Controllers/IPPController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.Practices.Unity;
using Resources;
using VAV.DAL.IPP;
using VAV.Web.Extensions;
using VAV.Web.Localization;
using VAV.Model.Data.IPP;
using VAV.Web.UserSetting;
using VAV.Web.ViewModels.IPP;
using VAV.Web.Common;
using System.Collections.Generic;
using System;
using VAV.Entities;
using System.Linq;
using System.Data;
using System.Collections;
using VAV.DAL.Common;


namespace VAV.Web.Controllers
{
    [Localization]
    public class IPPController : Controller
    {
        [Dependency]
        public IPPRepository IPPRepository { get; set; }

        public ActionResult IPPHome()
        {
            var isEnglish = CultureHelper.IsEnglishCulture();
            ViewBag.StaticTopics = IPPRepository.GetStaticTopics(isEnglish);
            ViewBag.Announcement = IPPRepository.GetAnnouncement(isEnglish);
            ViewBag.LatestFile = IPPRepository.GetLatestFile(isEnglish);
            ViewBag.InternalUser = UserSettingHelper.IsInternalUser(Request);

            var userAttibuteMap = UserSettingHelper.GetUserAttributeMap(Request);
            string submitterId;
            if (String.IsNullOrWhiteSpace(Request.Headers["reutersuuid"]))
                submitterId = Request.ServerVariables["HTTP_X_FORWARDED_FOR"] ?? Request.ServerVariables["REMOTE_ADDR"];
            else
                submitterId = userAttibuteMap == null ? "" : userAttibuteMap.First(x => x.name.ToLower() == "UserId".ToLower()).value;

            var email = userAttibuteMap == null ? "" : userAttibuteMap.First(x => x.name.ToLower() == "UserId".ToLower()).value;
            var name = userAttibuteMap == null ? "" : userAttibuteMap.First(x => x.name.ToLower() == "FullName".ToLower()).value;
            var RM = userAttibuteMap == null ? "" : userAttibuteMap.First(x => x.name.ToLower() == "ReutersMessagingId".ToLower()).value;

            IPPRepository.InsertSubmitter(submitterId, email, name, RM);

            return View();
        }

        public JsonResult GetHotTopic(string period,bool isHtml = false)
        {
            var data = IPPRepository.GetTopTopic(period, CultureHelper.IsEnglishCulture());
            return isHtml ? Json(data, "text/html", JsonRequestBehavior.AllowGet) : Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetHotFile(string period,bool isHtml = false)
        {
            var data = IPPRepository.GetTopFile(period, CultureHelper.IsEnglishCulture());
            return isHtml ? Json(data, "text/html", JsonRequestBehavior.AllowGet) : Json(data, JsonRequestBehavior.AllowGet);
        }

        #region File Editor
        public ActionResult FileEditor(long? id, int? topicid, string previousRequest)
        {
            FileCreate fileCreate = null; 
            
            if (id == null)
            {
                fileCreate = new FileCreate();
                var eikonUserId = UserSettingHelper.GetEikonUserID(Request);
                var submitter = IPPRepository.GeSubmitterById(eikonUserId);

                fileCreate.SubmitterID = submitter.ID;
                fileCreate.SubmiterName = submitter.Name;
                fileCreate.Submiter = submitter.Email;
            }
            else 
                fileCreate =  IPPRepository.GetFileByFileID((long)id);

            IPPFile ippFile;

            fileCreate = fileCreate ?? new FileCreate();
            var moduleItems = new List<SelectListItem>();
            var topicItems = new List<SelectListItem>();
            var ricTypeItems = new List<SelectListItem>();
            var uploadTypeItems = HtmlUtil.CookSelectOptions("Ipp_UploadType");

            if (id != null)
            {
                topicid = IPPRepository.GetTopicIdByFileId(id);
            }

            IEnumerable<MODULEINFO>  modules = IPPRepository.GetModuleList();
            var moduleId = (topicid == null || topicid == 0)? modules.FirstOrDefault().ID : (int)IPPRepository.GetModuleIdByTopicId((int)topicid);
            var topics = IPPRepository.GetTopicListByModuleId(moduleId);

            foreach (var m in modules)
            {
                moduleItems.Add(new SelectListItem { Selected = m.ID == moduleId ? true : false, Value = m.ID.ToString(), Text = CultureHelper.IsEnglishCulture() ? m.NAMEEN : m.NAMECN  });
            }

            var selectedTopicId = topicid == null ? topics.FirstOrDefault().ID : topicid;
            foreach (var m in topics)
            {
                topicItems.Add(new SelectListItem { Selected = m.ID == selectedTopicId ? true : false, Value = m.ID.ToString(), Text = CultureHelper.IsEnglishCulture() ? m.NAMEEN : m.NAMECN });
            }

            ricTypeItems.Add(new SelectListItem { Value = "Graph", Text = "Chart" });
            ricTypeItems.Add(new SelectListItem { Value = "Quote Object", Text = "Quote" });
            ricTypeItems.Add(new SelectListItem { Value = "News", Text = "News" });

            var userAttibuteMap = UserSettingHelper.GetUserAttributeMap(Request);
            var author = userAttibuteMap == null ? "" : userAttibuteMap.First(x => x.name.ToLower() == "FullName".ToLower()).value;
            var source = userAttibuteMap == null ? "" : userAttibuteMap.First(x => x.name.ToLower() == "AccountName".ToLower()).value;

            if (UserSettingHelper.IsInternalUser(Request))
                source = "Thomson Reuters";

            ippFile = new IPPFile
            {
                Id = fileCreate.ID,
                Author = string.IsNullOrEmpty(fileCreate.Author) ? author : fileCreate.Author,
                AuthorRM = fileCreate.AuthorRM,
                AuthorEmail = fileCreate.AuthorEmail,
                DescriptionCn = fileCreate.DescrCn,
                DescriptionEn = fileCreate.DescrEn,
                UploadType = fileCreate.UploadType,
                FileType = fileCreate.FileType,
                WebsiteRic = fileCreate.UploadType == "Upload_Website" ? fileCreate.RIC : "",
                EikonRic = fileCreate.UploadType == "Upload_Ric" ? fileCreate.RIC : "",
                ReportDate = fileCreate.ReportDate.ToString("yyyy-MM-dd"),
                SubmitterID = fileCreate.SubmitterID,
                SubmiterName = fileCreate.SubmiterName,
                Submiter = fileCreate.Submiter,
                Tag = fileCreate.Tag != null ? fileCreate.Tag.Replace('|', ';') : fileCreate.Tag,
                TitleCn = fileCreate.TitleCn,
                TitleEn = fileCreate.TitleEn,
                ModuleItems = moduleItems,
                Topic = selectedTopicId.ToString(),
                TopicItems = topicItems,
                UploadTypeItems = uploadTypeItems,
                RicTypeItems = ricTypeItems,
                Source = string.IsNullOrEmpty(fileCreate.Source) ? source : fileCreate.Source,
                PreviousRequest = previousRequest,
                Status = fileCreate.Status,
                FileName = fileCreate.FileName,
                DisplayOrder = fileCreate.DisplayOrder
            };

            return View(ippFile);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(IPPFile ippFile, HttpPostedFileBase file, string submit)
        {
            string fileType = "";
            string ric = "";

            if (ippFile.UploadType == "Upload_File")
            {
                if (file != null)
                {
                    var index = file.FileName.LastIndexOf(".");
                    fileType = file.FileName.Substring(index + 1);
                }
                else {
                    var index = ippFile.FileName.LastIndexOf(".");
                    fileType = ippFile.FileName.Substring(index + 1);
                }
            }
            else
            {
                fileType = ippFile.FileType;
            }

            if (ippFile.UploadType == "Upload_Website")
            {
                if (!ippFile.WebsiteRic.Contains("cpurl://"))
                {
                    if (!ippFile.WebsiteRic.Contains("http"))
                        ippFile.WebsiteRic = "http://" + ippFile.WebsiteRic;
                }

                ric = ippFile.WebsiteRic;
            }
            else if (ippFile.UploadType == "Upload_Ric")
            {
                ric = ippFile.EikonRic;
            }

            var fileCreate = new FileCreate
            {
                ID = ippFile.Id ?? 0,  /*0 to indicated 'insert'*/
                Author = ippFile.Author,
                AuthorRM = ippFile.AuthorRM,
                AuthorEmail = ippFile.AuthorEmail,
                DescrCn = ippFile.DescriptionCn,
                DescrEn = ippFile.DescriptionEn,
                UploadType = ippFile.UploadType,
                FileType = fileType,
                RIC = ric,
                SubmitDate = DateTime.Now,
                ReportDate = DateTime.Parse(ippFile.ReportDate),
                SubmitterID = ippFile.SubmitterID,
                Tag = ippFile.Tag == null ? "" : ippFile.Tag.Replace(';', '|').Replace('；', '|'),
                TitleCn = ippFile.TitleCn,
                TitleEn = ippFile.TitleEn,
                TopicID = Convert.ToInt32(ippFile.Topic),
                Source = ippFile.Source,
                FileName = ippFile.FileName,
                DisplayOrder = ippFile.DisplayOrder
            };

            if (file != null && file.ContentLength > 0)
            {
                fileCreate.Doc = new byte[file.ContentLength];
                file.InputStream.Read(fileCreate.Doc, 0, file.ContentLength);
            }

            fileCreate.Status = submit == Resources.IPP.IPP_Save ? 0 : -1; //-1: publish
            IPPRepository.UploadFile(fileCreate);

            switch (ippFile.PreviousRequest)
            {
                case "fileBrowser":
                    return RedirectToAction("FileBrowser", new { id = fileCreate.TopicID });

web/VAV.Web/Views/IPP/FileEditor.cshtml
@model VAV.Web.ViewModels.IPP.IPPFile
@using System.Threading

@{
    Layout = null;
    ViewBag.Title = "File Editor";
    var datePickerId = "ReportDate";
    var fileSizeAlert = Resources.IPP.IPP_File_Size_Alert;
    var status = Model.Status;
    @Scripts.Render("~/bundles/jqueryval")
}

<div class="colorBlock" style="height:640px; margin-top:5px; min-width: 800px; overflow:auto;">
    <div class="colorBlock-header">
        <span class="colorBlock-header-span">@Resources.IPP.IPP_Uplaod_Header</span>
    </div>
    @using (Html.BeginForm("Upload", "IPP", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div style="color:Red;">
            @Html.ValidationSummary()
            @Html.AntiForgeryToken()
            <div id="alertMessage"></div>
        </div>
            
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.PreviousRequest)
        @Html.HiddenFor(m => m.SubmitterID)
        @Html.HiddenFor(m => m.Submiter)

        <ol class="IPP_ol">
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Title_Cn *</label></div>
                @Html.TextBoxFor(m => m.TitleCn, new { @class = "IPPFELargeDiv" })
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Title_En *</label></div>
                @Html.TextBoxFor(m => m.TitleEn, new { @class = "IPPFELargeDiv" })
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Module</label></div>
                @Html.DropDownListFor(m => m.Module, @Model.ModuleItems, new Dictionary<string, object> { { "onchange", "javascript:FileEditor.UpdateTopicOption('#Module', '#Topic');" }, { "class", "IPPFEDpl" } })
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Topic</label></div>
                @Html.DropDownListFor(m => m.Topic, @Model.TopicItems, new { @class = "IPPFEDpl" })
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Desc_Cn</label></div>
                @Html.TextAreaFor(m => m.DescriptionCn, new { @class = "IPPFETextArea" })
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Desc_En</label></div>
                @Html.TextAreaFor(m => m.DescriptionEn, new { @class = "IPPFETextArea" })
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Upload_Type</label></div>
                @Html.DropDownListFor(m => m.UploadType, Model.UploadTypeItems, new Dictionary<string, object> { { "onchange", "javascript:FileEditor.UpdateUpload();" }, { "class", "IPPFEDpl" } })
            </li>
            <li id="Upload_Website" tag="upload">
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Website</label></div>
                @Html.TextBoxFor(m => m.WebsiteRic, new { @class = "IPPFELargeDiv" })
            </li>
            <li id="Upload_File" tag="upload">
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_File</label></div>
                @Html.TextBoxFor(m => m.FileName, new { @style="margin-left:15px; width:570px;", @readonly = "readonly" })
                <input type="button" style="width:77px;" value="@Resources.IPP.IPP_Upload" id="uploadBtn" onclick="FileEditor.Upload()" />
                <input type="file" name="file" id="file" style="display:none"/>
            </li>
            <li id="Upload_Ric" tag="upload">
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Ric_Type</label></div>
                <div style="float:left;">@Html.DropDownListFor(m => m.FileType, @Model.RicTypeItems, new { @style = "width: 114px; margin-left: 15px;" })</div>
                <div class="IPPFERightLabel"><label>RIC</label></div>
                @Html.TextBoxFor(m => m.EikonRic, new { @class = "IPPFEMiddleDiv" })
            </li>
            <li >
                <div class="IPPFELeftLabel"><label>@Resources.IPP.Top</label></div>
                <div style="float: left;">@Html.CheckBoxFor(m => m.IsSetTop, new { style = "margin-left: 15px;" })</div>
                <div style="clear: both;"></div>
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Create_Date</label></div>
                <div style="float:left;">@Html.TextBoxFor(m => m.ReportDate, new { @readonly = "readonly", @class = "IPPFESmallDiv" })</div>
                <div class="IPPFERightLabel" style="padding-top:3px;"><label>@Resources.IPP.IPP_Author</label></div>
                <div style="float:left;">
                    @Html.TextBoxFor(m => m.Author, new { @style = "width: 55px; margin-left: 15px;" })
                </div>    
                <div class="IPPFERightLabel" style="width:70px;padding-top:3px;"><label>@Resources.IPP.IPP_Source</label></div>
                @Html.TextBoxFor(m => m.Source, new { @style = "width: 265px; margin-left: 19px;" })
            </li>
            <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Author_Email</label></div>
                <div style="float:left;">@Html.TextBoxFor(m => m.AuthorEmail, new { @class = "IPPFESmallDiv" })</div>
                <div class="IPPFERightLabel"><label>@Resources.IPP.IPP_Author_Rm</label></div>
                @Html.TextBoxFor(m => m.AuthorRM, new { @class = "IPPFESpecialDiv" })
            </li>
                <li>
                <div class="IPPFELeftLabel"><label>@Resources.IPP.IPP_Submiter</label></div>
                <div style="float:left;">@Html.TextBoxFor(m => m.SubmiterName, new { @class = "IPPFESmallDiv", @readonly = "readonly" })</div>
                <div class="IPPFERightLabel"><label>@Resources.IPP.IPP_Tag</label></div>
                @Html.TextBoxFor(m => m.Tag, new { @class = "IPPFESpecialDiv", placeholder = @Resources.IPP.IPP_Sperator, onfocus = "this.placeholder = ''", onblur = "this.placeholder = '" + @Resources.IPP.IPP_Sperator + "'" })
            </li>
        </ol>
        <div style="margin: 20px 0px 0px 350px">
            <input type="submit" value="@Resources.IPP.IPP_Save" name="submit" id="saveBtn" onclick="return FileEditor.CheckFile()"/>
            <input class="toggle" type="submit" value="@Resources.IPP.IPP_Publish" name="submit" id="submitBtn" onclick="return FileEditor.CheckFile()"/>
            <input class="toggle" style="display:none;" type="submit" value="@Resources.IPP.IPP_Cancle" id="cancleBtn" onclick="$('#tempDailog').dialog('close');return false;" />
        </div>
    }
</div>
<script type="text/javascript">

    var FileEditor = (function (my) {
        my.CheckFile = function () {
            var uploadType = $('#UploadType option:selected').val();
            if (uploadType == 'Upload_File') {
                var fileList = $("#file")[0].files;
                if (fileList.length == 0 && $('#FileName').val() == '') {
                    $('#alertMessage').text('@Resources.IPP.IPP_File_Not_Null');
                    return false;
                }
                $("#alertMessage").text('');
                for (var i = 0, file; file = fileList[i]; i++) {
                    if (file.size > (5 * 1024 * 1024)) {
                        $('#alertMessage').text('@Resources.IPP.IPP_File_Size_Alert');
                        return false;
                    } else {
                        return true;
                    }
                }
            }
            else if (uploadType == 'Upload_Website') {
                if ($('#WebsiteRic').val() == '') {
                    $("#alertMessage").text('@Resources.IPP.IPP_WebSite_Not_Null');
                    return false;
                }
            }
            else {
                if ($('#EikonRic').val() == '') {
                    $("#alertMessage").text('@Resources.IPP.IPP_RIC_Not_Null');
                    return false;
                }
            }
        };

        my.BuildTopicSelect = function (sl, data) {
            var markup = FileEditor.BuildTopicOptionTempl();
            $.template("optionTemplate", markup);
            $(sl + ' option').remove();
            $.tmpl("optionTemplate", data).appendTo(sl);
        };

        my.BuildTopicOptionTempl = function () {
            var tpl = '<option value="${Id}">';
            tpl = tpl + '${Name}</option>';
            return tpl;
        };

        my.UpdateTopicOption = function (module, topicSl) {
            var id = $(module).val();
            $.ajax({
                type: 'Get',
                url: '/IPP/UpdateTopicByModule',
                data: { id: id },
                success: function (data) {
                    FileEditor.BuildTopicSelect(topicSl, data);
                },
                error: function () {
                    debugger;
                },
                async: true
            });
        };

        my.UpdateUpload = function () {
            var id = $("#UploadType").val();
            $("li[id!='" + id + "'][tag='upload']").hide();
            $("#" + id).show();
        }

        my.Upload = function (){
            $('#file').trigger('click');
        }

        return my;
    } (FileEditor || {}))

    $(function () {
        FileEditor.UpdateUpload();

        $('#file').bind('change', function () {
            var fileList = $("#file")[0].files;
            for (var i = 0, file; file = fileList[i]; i++) {
                var fileName = file.name.split('.')[0];
                if ($('#TitleCn').val() == '' && $('#TitleEn').val() == '') {
                    $('#TitleCn').val(fileName);
                    $('#TitleEn').val(fileName);
                };
                $('#FileName').val(file.name);
            }
        });

        $.datepicker.setDefaults($.datepicker.regional["@Thread.CurrentThread.CurrentUICulture.Name"]);

        $("#@datePickerId").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd'
        });

        if (@status == 2) { 
            $('#Module option:not(:selected)').prop('disabled', true);
            $('#Topic option:not(:selected)').prop('disabled', true);
            $('.toggle').toggle();
        }
    }); 

</script>

web/VAV.Web/Views/IPP/MyDocument.cshtml
@Scripts.Render("~/js/angular")
@Scripts.Render("~/js/ippCommon")
@Scripts.Render("~/js/ippMyDocument")
<div class="colorBlock" data-ng-app="mydocument" data-ng-controller="MainCtl">
    <div class="colorBlock-header">
        <span class="colorBlock-header-span">@Resources.IPP.IPP_MyDocument</span>
    </div>
    <div class="ippTab ui-tabs ui-widget ui-widget-content">
        <ul class="ui-tabs-nav ui-helper-clearfix">
            <li><a href="/ipp/MyDocument/FavoriteFiles" data-ng-class="{active: selectTab=='myFavorites'}">@Resources.IPP.IPP_MyFavorite</a></li>
            <li><a href="/ipp/MyDocument/prePublish" data-ng-class="{active: selectTab=='prePublish'}">@Resources.IPP.IPP_PrePublished</a></li>
            <li><a href="/ipp/MyDocument/published" data-ng-class="{active: selectTab=='published'}">@Resources.IPP.IPP_Published</a></li>
             @if (ViewBag.InternalUser)
             {
                 <li><a href="/ipp/MyDocument/preApprove" data-ng-class="{active: selectTab=='preApprove'}">@Resources.IPP.IPP_PendingApprove</a></li>
                 <li><a href="/ipp/MyDocument/approved" data-ng-class="{active: selectTab=='approved'}">@Resources.IPP.IPP_Approveds</a></li>
                 <li><a href="/ipp/MyDocument/topicManagement" data-ng-class="{active: selectTab=='topicManagement'}">@Resources.IPP.IPP_TopicManagement</a></li>
             }
        </ul>
        <div data-ng-view></div>
    </div>
    <hr/>
</div>

web/VAV.Web/Views/IPP/_IPPLayout.cshtml
@using VAV.Web.Common
@using VAV.Web.Localization
@{
    var busyImageUrl = VirtualPathUtility.ToAbsolute("~/Content/images/loading.gif");
}
<!DOCTYPE html>
<html>
    <head>
        <script type="text/javascript">
            window.Common = {};
            window.Common.ChartSource = '@Resources.Global.Source';
        </script>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title></title>
        @{
            var bundleCSSPath = string.Format("~/Content/themes/{0}/IPPbundle", ThemeHelper.GetTheme(Request));     
        }
        @Styles.Render(bundleCSSPath)
        <script type="text/javascript">
            window.busyImageUrl = '@busyImageUrl';
            window.isEn = @CultureHelper.IsEnglishCulture().ToString().ToLower();
        </script>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui/IPP")
        @Scripts.Render("~/bundles/JET")
        @Scripts.Render("/bundles/highcharts")
        @if (CultureHelper.IsEnglishCulture())
        {
            @Scripts.Render("~/bundles/ippjslangen")
        }
        else
        {
            @Scripts.Render("~/bundles/ippjslangzh")
        }
        @{
            var themeName = ThemeHelper.GetTheme(Request);        
        }

        @(themeName == "Pearl" ? Scripts.Render("~/bundles/pearltheme") : Scripts.Render("~/bundles/novatheme"))
        <script>
            $(function () {
                JET.init({ ID: "VAVWeb"});
            });
        </script>
    </head>
<body>
    @RenderBody()
</body>
</html>